# Top Image
disable_top_img: true

# Dark mode
darkmode:
  enable: true
  # dark mode和 light mode切換按鈕
  button: true
  autoChangeMode: 1
  # Set the light mode time. The value is between 0 and 24. If not set, the default value is 6 and 18
  start: # 8
  end: # 22

# Menu
menu:
  關於我: /about || fas fa-user

# Social
social:
  fab fa-github: https://github.com/hao0731 || Github || "#hdhfbb"
  fa-solid fa-globe: https://ithelp.ithome.com.tw/users/20119338 || iT邦幫忙 || "#000000"

# Avatar
avatar:
  img: /images/avatar.png
  effect: false # 頭像會一直轉圈

# Aside
aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  display:
    archive: true
    tag: true
    category: true
  card_author:
    enable: true
    description: 樂於分享與熱愛學習的工程師
    button:
      enable: false
      # icon: fab fa-github
      # text: Follow Me
      # link: https://github.com/xxxxxx
  card_announcement:
    enable: true
    content: 全世界第一本繁體中文 NestJS 入門書籍已上架，歡迎點擊<a href="https://www.tenlong.com.tw/products/9786263332935">這裡</a>前往購買！
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: 1
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: 1
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: 1
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: false
    orderby: random # Order of tags, random/name/length
    order: 1 # Sort of order. 1, asc for ascending; -1, desc for descending
    sort_order: 1
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: true
    sort_order: 1


# Page meta
post_meta:
  page:
    date_type: both # created or updated or both 主頁文章日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 主頁是否顯示分類
    tags: true # true or false 主頁是否顯示標籤
    label: true # true or false 顯示描述性文字
  post:
    date_type: both # created or updated or both 文章頁日期是創建日或者更新日或都顯示
    date_format: relative # date/relative 顯示日期還是相對日期
    categories: true # true or false 文章頁是否顯示分類
    tags: true # true or false 文章頁是否顯示標籤
    label: true # true or false 顯示描述性文字

# Code
highlight_theme: mac
highlight_shrink: none

# Copyright
post_copyright:
  enable: true
  decode: false
  author_href:
  license: CC BY-NC-SA 4.0
  license_url: https://creativecommons.org/licenses/by-nc-sa/4.0/

# Share
sharejs:
  enable: false

# Footer
footer:
  owner:
    enable: true
    since: 2023

mermaid:
  enable: true
  theme:
    light: default
    dark: dark

# 404
error_404:
  enable: true